version: '3'
services:
  myexpressapi:
    build: ./express
    ports:
     - "3000:3000"
    restart: always
  nginx: 
    build: ./nginx 
    ports: 
      - "80:80" 
    links: 
     - myexpressapi
